import type {
  Coach,
  DfsPlayer,
  Game,
  PortalEvent,
  ProviderHealth,
  ScenarioGame,
  SeasonRules,
  Stadium,
  Team,
} from "./types";

const asOf = "2026-07-31T08:00:00.000Z";

function fixtureProvenance(id: string, modelVersion?: string) {
  return {
    provider: "Duke Fantasy deterministic fixture provider",
    providerRecordId: `fixture:${id}`,
    sourceDocumentId: "fixture-pack-2026.07.31",
    sourceAsOf: asOf,
    fetchedAt: asOf,
    verifiedAt: asOf,
    verificationStatus: "synthetic" as const,
    licenseClass: "R0_FIXTURE" as const,
    confidence: 1,
    dataEnvironment: "fixture" as const,
    recordOrigin: modelVersion ? ("model" as const) : ("fixture" as const),
    freshness: "current" as const,
    modelVersion,
  };
}

const teamRows = [
  ["north-coast", "North Coast Navigators", "North Coast", "NCO", "NC", "Northern", "P4", 1, "10–1", "#55C7C2", 91, 78, 8.4, 82],
  ["prairie-tech", "Prairie Tech Bison", "Prairie Tech", "PTB", "PT", "Heartland", "P4", 4, "9–2", "#F2B84B", 87, 71, 5.9, 69],
  ["tidewater-state", "Tidewater State Admirals", "Tidewater", "TSA", "TS", "Atlantic", "P4", 7, "9–2", "#65C7F2", 84, 65, -1.6, 58],
  ["red-mesa", "Red Mesa Copperheads", "Red Mesa", "RMC", "RM", "Frontier", "P4", 9, "8–3", "#E67955", 82, 63, 10.1, 47],
  ["lake-union", "Lake Union Owls", "Lake Union", "LUO", "LU", "Northern", "P4", 12, "8–3", "#9EBB72", 79, 81, -3.1, 35],
  ["blue-ridge-state", "Blue Ridge State Peaks", "Blue Ridge", "BRS", "BR", "Atlantic", "P4", 14, "8–3", "#8DA7F7", 78, 69, 2.4, 31],
  ["gulf-poly", "Gulf Polytechnic Pelicans", "Gulf Poly", "GPP", "GP", "Coastal", "G5", 18, "10–1", "#55D59B", 77, 72, 6.7, 28],
  ["canyon-ag", "Canyon A&M Roadrunners", "Canyon A&M", "CAM", "CA", "Frontier", "P4", 20, "7–4", "#D99367", 75, 56, 4.2, 22],
  ["great-plains", "Great Plains State Pronghorns", "Great Plains", "GPS", "GS", "Heartland", "P4", 22, "7–4", "#E7CD75", 74, 77, -2.2, 18],
  ["metro-central", "Metro Central Comets", "Metro Central", "MCC", "MC", "Independent", "G5", 24, "9–2", "#B48CF2", 73, 68, 7.8, 16],
  ["pine-valley", "Pine Valley State Foxes", "Pine Valley", "PVS", "PV", "Coastal", "G5", undefined, "8–3", "#78C89C", 70, 74, 1.9, 10],
  ["iron-range", "Iron Range Miners", "Iron Range", "IRM", "IR", "Northern", "P4", undefined, "6–5", "#BAC3CC", 69, 52, -5.1, 7],
  ["capital-city", "Capital City Union", "Capital City", "CCU", "CC", "Atlantic", "P4", undefined, "6–5", "#E98B7A", 68, 61, 3.2, 5],
  ["delta-state-tech", "Delta State Tech Herons", "Delta Tech", "DST", "DT", "Coastal", "G5", undefined, "8–3", "#6ECAD0", 67, 70, 9.5, 4],
  ["western-lakes", "Western Lakes Mariners", "Western Lakes", "WLM", "WL", "Frontier", "G5", undefined, "7–4", "#6E9DD0", 65, 58, -0.8, 3],
  ["heritage-college", "Heritage College Founders", "Heritage", "HCF", "HC", "Pioneer", "FCS", undefined, "10–1", "#D4A667", 63, 80, 4.9, 1],
] as const;

export const teams: Team[] = teamRows.map(
  ([slug, name, shortName, abbreviation, monogram, conference, subdivision, rank, record, color, strength, returningProduction, portalImpact, playoffProbability], index) => ({
    id: `team-${index + 1}`,
    slug,
    name,
    shortName,
    abbreviation,
    monogram,
    conference,
    subdivision,
    rank,
    record,
    color,
    strength,
    returningProduction,
    portalImpact,
    playoffProbability,
    provenance: fixtureProvenance(`team-${index + 1}`),
  }),
);

const id = (slug: string) => {
  const team = teams.find((candidate) => candidate.slug === slug);
  if (!team) throw new Error(`Unknown fixture team slug: ${slug}`);
  return team.id;
};

export const games: Game[] = [
  {
    id: "game-nco-ptb",
    week: 12,
    date: "2026-11-14T20:30:00.000Z",
    kickoffLabel: "Sat · 12:30 PM PT",
    status: "scheduled",
    statusDetail: "Kickoff scheduled",
    awayTeamId: id("prairie-tech"),
    homeTeamId: id("north-coast"),
    venueSlug: "harbor-field",
    venue: "Harbor Field",
    city: "Port Sterling, OR",
    broadcast: "National broadcast destination pending licensed provider",
    weather: { temperature: 52, summary: "Light rain possible", windMph: 9 },
    neutralSite: false,
    modelHomeWinProbability: 0.64,
    modelUncertainty: 0.08,
    line: { home: -3.5, movement: [-2.5, -3, -3, -3.5, -3.5], asOf },
    provenance: fixtureProvenance("game-nco-ptb", "matchup-2026.3.0-demo"),
  },
  {
    id: "game-tsa-rmc",
    week: 12,
    date: "2026-11-14T23:00:00.000Z",
    kickoffLabel: "Sat · 3:00 PM PT",
    status: "scheduled",
    statusDetail: "Kickoff scheduled",
    awayTeamId: id("tidewater-state"),
    homeTeamId: id("red-mesa"),
    venueSlug: "sunstone-stadium",
    venue: "Sunstone Stadium",
    city: "Mesa Verde, AZ",
    broadcast: null,
    weather: { temperature: 68, summary: "Clear and dry", windMph: 4 },
    neutralSite: false,
    modelHomeWinProbability: 0.53,
    modelUncertainty: 0.11,
    line: { home: -1.5, movement: [-2.5, -2, -1.5, -1.5], asOf },
    provenance: fixtureProvenance("game-tsa-rmc", "matchup-2026.3.0-demo"),
  },
  {
    id: "game-gpp-mcc",
    week: 12,
    date: "2026-11-15T01:30:00.000Z",
    kickoffLabel: "Sat · 5:30 PM PT",
    status: "delayed",
    statusDetail: "Demonstration delay state · kickoff time pending",
    awayTeamId: id("gulf-poly"),
    homeTeamId: id("metro-central"),
    venueSlug: "orbit-park",
    venue: "Orbit Park",
    city: "Central City, MO",
    broadcast: "Provider not configured",
    weather: null,
    neutralSite: false,
    modelHomeWinProbability: 0.43,
    modelUncertainty: 0.14,
    provenance: fixtureProvenance("game-gpp-mcc", "matchup-2026.3.0-demo"),
  },
  {
    id: "game-luo-brs",
    week: 11,
    date: "2025-11-07T20:00:00.000Z",
    kickoffLabel: "Final",
    status: "final",
    statusDetail: "Final · 2OT",
    awayTeamId: id("lake-union"),
    homeTeamId: id("blue-ridge-state"),
    awayScore: 31,
    homeScore: 34,
    venueSlug: "summit-bowl",
    venue: "Summit Bowl",
    city: "Asheville, NC",
    broadcast: "Replay destination unavailable in fixture mode",
    weather: { temperature: 48, summary: "Cloudy", windMph: 7 },
    neutralSite: false,
    modelHomeWinProbability: 0.55,
    modelUncertainty: 0.09,
    provenance: fixtureProvenance("game-luo-brs", "matchup-2026.3.0-demo"),
  },
  {
    id: "game-pvs-dst",
    week: 12,
    date: "2026-11-14T18:00:00.000Z",
    kickoffLabel: "Time TBA",
    status: "postponed",
    statusDetail: "Demonstration postponed state · new date unavailable",
    awayTeamId: id("pine-valley"),
    homeTeamId: id("delta-state-tech"),
    venueSlug: "marshlight-field",
    venue: "Marshlight Field",
    city: "Delta City, LA",
    broadcast: null,
    weather: null,
    neutralSite: false,
    modelHomeWinProbability: 0.51,
    modelUncertainty: 0.16,
    provenance: fixtureProvenance("game-pvs-dst", "matchup-2026.3.0-demo"),
  },
];

export const portalEvents: PortalEvent[] = [
  {
    id: "portal-1",
    playerSlug: "micah-reed",
    player: "Micah Reed",
    position: "QB",
    fromTeamId: id("western-lakes"),
    toTeamId: id("red-mesa"),
    status: "committed",
    eventDate: "2026-05-07",
    snaps: 612,
    usage: 0.78,
    impact: null,
    confidence: "high",
    provenance: fixtureProvenance("portal-1", "portal-impact-2026.2.1-demo"),
  },
  {
    id: "portal-2",
    playerSlug: "darius-cole",
    player: "Darius Cole",
    position: "EDGE",
    fromTeamId: id("north-coast"),
    toTeamId: id("gulf-poly"),
    status: "committed",
    eventDate: "2026-05-03",
    snaps: 488,
    usage: 0.64,
    impact: null,
    confidence: "high",
    provenance: fixtureProvenance("portal-2", "portal-impact-2026.2.1-demo"),
  },
  {
    id: "portal-3",
    playerSlug: "eli-vaughn",
    player: "Eli Vaughn",
    position: "WR",
    fromTeamId: id("capital-city"),
    toTeamId: null,
    status: "available",
    eventDate: "2026-05-01",
    snaps: 332,
    usage: 0.41,
    impact: null,
    confidence: "medium",
    provenance: fixtureProvenance("portal-3", "portal-impact-2026.2.1-demo"),
  },
  {
    id: "portal-4",
    playerSlug: "jonah-price",
    player: "Jonah Price",
    position: "OL",
    fromTeamId: id("prairie-tech"),
    toTeamId: id("lake-union"),
    status: "committed",
    eventDate: "2026-04-29",
    snaps: 731,
    usage: null,
    impact: null,
    confidence: "medium",
    provenance: fixtureProvenance("portal-4", "portal-impact-2026.2.1-demo"),
  },
  {
    id: "portal-5",
    playerSlug: "omar-fields",
    player: "Omar Fields",
    position: "CB",
    fromTeamId: id("heritage-college"),
    toTeamId: id("metro-central"),
    status: "committed",
    eventDate: "2026-04-26",
    snaps: null,
    usage: null,
    impact: null,
    confidence: "low",
    provenance: fixtureProvenance("portal-5", "portal-impact-2026.2.1-demo"),
  },
];

export const seasonRules: SeasonRules = {
  id: "demo-rules-2026",
  season: 2026,
  label: "2026 demonstration 12-team format",
  playoffTeams: 12,
  byes: 4,
  membershipVersion: "fixture-membership-2026.1",
  seedingVersion: "fixture-seeding-2026.1",
  sourceStatus: "fixture",
  asOf,
};

export const scenarioGames: ScenarioGame[] = [
  { id: "scenario-1", awayTeamId: id("prairie-tech"), homeTeamId: id("north-coast"), week: 12 },
  { id: "scenario-2", awayTeamId: id("tidewater-state"), homeTeamId: id("red-mesa"), week: 12 },
  { id: "scenario-3", awayTeamId: id("gulf-poly"), homeTeamId: id("metro-central"), week: 12 },
  { id: "scenario-4", awayTeamId: id("great-plains"), homeTeamId: id("blue-ridge-state"), week: 13 },
];

export const coaches: Coach[] = [
  {
    id: "coach-1",
    slug: "mara-vance",
    name: "Mara Vance",
    teamId: id("capital-city"),
    title: "Head coach",
    contractStart: "2023-01-01",
    contractEnd: "2028-12-31",
    annualSalary: 5_200_000,
    guaranteedRemaining: 13_000_000,
    offsetEstimate: 2_000_000,
    mitigationApplies: true,
    hotSeatIndex: 78,
    hotSeatCoverage: 0.84,
    record: "19–17",
    timeline: [
      { date: "2026-07-01", label: "Contract terms re-verified for fixture pack", kind: "verified" },
      { date: "2025-12-01", label: "Season finished 6–6", kind: "context" },
      { date: "2023-01-05", label: "Named head coach", kind: "verified" },
    ],
    provenance: fixtureProvenance("coach-1", "hot-seat-2026.1.2-demo"),
  },
  {
    id: "coach-2",
    slug: "theo-banks",
    name: "Theo Banks",
    teamId: id("iron-range"),
    title: "Interim head coach",
    contractStart: "2025-09-20",
    contractEnd: "2026-12-31",
    annualSalary: 1_200_000,
    guaranteedRemaining: 400_000,
    offsetEstimate: 0,
    mitigationApplies: false,
    hotSeatIndex: 42,
    hotSeatCoverage: 0.58,
    record: "4–3 interim",
    timeline: [
      { date: "2025-09-20", label: "Appointed interim head coach", kind: "verified" },
      { date: "2026-07-01", label: "Served as defensive coordinator", kind: "context" },
    ],
    provenance: fixtureProvenance("coach-2", "hot-seat-2026.1.2-demo"),
  },
  {
    id: "coach-3",
    slug: "jules-hart",
    name: "Jules Hart",
    teamId: id("prairie-tech"),
    title: "Head coach",
    contractStart: "2022-01-01",
    contractEnd: "2030-12-31",
    annualSalary: 7_400_000,
    guaranteedRemaining: 29_600_000,
    offsetEstimate: 7_000_000,
    mitigationApplies: true,
    hotSeatIndex: 18,
    hotSeatCoverage: 0.91,
    record: "42–12",
    timeline: [
      { date: "2026-01-10", label: "Extension entered fixture record", kind: "verified" },
      { date: "2025-12-20", label: "Conference title appearance", kind: "context" },
    ],
    provenance: fixtureProvenance("coach-3", "hot-seat-2026.1.2-demo"),
  },
];

export const dfsPlayers: DfsPlayer[] = [
  ["dfs-1", "micah-reed", "Micah Reed", id("red-mesa"), "QB", "Main", 8600, 17.2, 23.8, 31.6, "34.5 attempts + 5.8 carries", "Pass-friendly, high pace", "active"],
  ["dfs-2", "sawyer-knox", "Sawyer Knox", id("north-coast"), "QB", "Main", 9100, 18.9, 25.4, 33.1, "32.0 attempts + 7.2 carries", "Balanced, moderate weather", "active"],
  ["dfs-3", "malik-snow", "Malik Snow", id("gulf-poly"), "RB", "Main", 7200, 11.8, 17.6, 25.9, "18.4 carries + 3.2 targets", "Strong rushing leverage", "questionable"],
  ["dfs-4", "cameron-vale", "Cameron Vale", id("tidewater-state"), "WR", "Late", 6800, 10.6, 16.9, 24.8, "9.1 targets", "Secondary allows explosive plays", "active"],
  ["dfs-5", "niko-west", "Niko West", id("metro-central"), "WR", "Late", 5900, 8.2, 13.7, 21.4, "7.4 targets", "Trailing script increases volume", "active"],
  ["dfs-6", "asher-lane", "Asher Lane", id("lake-union"), "TE", "Main", 4800, 0, 0, 0, "Inactive · zero projected volume", "Inactive players remain zeroed", "inactive"],
] .map(([playerId, slug, name, teamId, position, slate, salary, floor, median, ceiling, projectedVolume, matchup, availability]) => ({
  id: playerId,
  slug,
  name,
  teamId,
  position,
  slate,
  salary,
  floor,
  median,
  ceiling,
  projectedVolume,
  matchup,
  availability,
  modelVersion: "dfs-2026.4.0-demo",
  provenance: fixtureProvenance(playerId as string, "dfs-2026.4.0-demo"),
})) as DfsPlayer[];

export const stadiums: Stadium[] = [
  {
    slug: "harbor-field",
    name: "Harbor Field",
    teamId: id("north-coast"),
    city: "Port Sterling, OR",
    address: "100 Harbor Way, Port Sterling, OR",
    capacity: 61200,
    parking: "Fixture guidance: north lots open four hours before kickoff; digital permit required.",
    transit: "Fixture shuttle loops run from the central transit station every 15 minutes.",
    clearBag: "Fixture policy: one clear 12 × 6 × 12 inch bag or a small clutch.",
    tailgating: "Fixture guidance: designated lots only; no open flame after kickoff.",
    visitorSection: "Fixture sections 124–127.",
    accessibility: "Step-free gates at north and east plazas; accessible shuttle reservations recommended.",
    lastVerified: "2026-07-31",
    provenance: fixtureProvenance("stadium-harbor"),
  },
  {
    slug: "sunstone-stadium",
    name: "Sunstone Stadium",
    teamId: id("red-mesa"),
    city: "Mesa Verde, AZ",
    address: "44 Copper Loop, Mesa Verde, AZ",
    capacity: 58400,
    parking: "Fixture guidance: prepaid desert lots and downtown park-and-ride.",
    transit: "Fixture light-rail service stops at Stadium Plaza.",
    clearBag: "Fixture policy: clear bags up to 12 × 6 × 12 inches.",
    tailgating: "Fixture guidance: shaded tailgate zone opens five hours before kickoff.",
    visitorSection: "Fixture sections 217–220.",
    accessibility: "Accessible parking in Copper Lot C with continuous cart service.",
    lastVerified: "2026-07-31",
    provenance: fixtureProvenance("stadium-sunstone"),
  },
  {
    slug: "orbit-park",
    name: "Orbit Park",
    teamId: id("metro-central"),
    city: "Central City, MO",
    address: "12 Launch Avenue, Central City, MO",
    capacity: 54600,
    parking: "Fixture guidance: prepaid east campus lots open four hours before kickoff.",
    transit: "Fixture shuttles connect the rail depot and downtown garage to Gate 2.",
    clearBag: "Fixture policy: one clear 12 × 6 × 12 inch bag or a small clutch.",
    tailgating: "Fixture guidance: marked campus lots only; generators must be attended.",
    visitorSection: "Fixture sections 118–121.",
    accessibility: "Step-free entry at Gates 1 and 2 with an accessible shuttle loop.",
    lastVerified: "2026-07-31",
    provenance: fixtureProvenance("stadium-orbit"),
  },
  {
    slug: "summit-bowl",
    name: "Summit Bowl",
    teamId: id("blue-ridge-state"),
    city: "Asheville, NC",
    address: "800 Ridge Road, Asheville, NC",
    capacity: 63800,
    parking: "Fixture guidance: west ridge permits are prepaid; remote lots include shuttle service.",
    transit: "Fixture express buses depart Union Center every 12 minutes.",
    clearBag: "Fixture policy: clear bags up to 12 × 6 × 12 inches.",
    tailgating: "Fixture guidance: tailgating closes 30 minutes after kickoff.",
    visitorSection: "Fixture sections 229–232.",
    accessibility: "Accessible drop-off is located at the south plaza with elevator access.",
    lastVerified: "2026-07-31",
    provenance: fixtureProvenance("stadium-summit"),
  },
  {
    slug: "marshlight-field",
    name: "Marshlight Field",
    teamId: id("delta-state-tech"),
    city: "Delta City, LA",
    address: "1 Lantern Walk, Delta City, LA",
    capacity: 57250,
    parking: "Fixture guidance: harbor garages require advance purchase; overflow parking uses shuttles.",
    transit: "Fixture ferry and bus service meet at Lantern Plaza.",
    clearBag: "Fixture policy: one clear 12 × 6 × 12 inch bag or a small clutch.",
    tailgating: "Fixture guidance: designated waterfront lots open five hours before kickoff.",
    visitorSection: "Fixture sections 301–304.",
    accessibility: "Step-free entry at Lantern Gate with accessible seating assistance nearby.",
    lastVerified: "2026-07-31",
    provenance: fixtureProvenance("stadium-marshlight"),
  },
];

export const providerHealth: ProviderHealth[] = [
  {
    id: "fixture-sports",
    label: "Sports data",
    mode: "fixture",
    status: "operational",
    lastSuccess: asOf,
    cadence: "Deterministic on every build",
    note: "Visible demonstration records only.",
  },
  {
    id: "production-sports",
    label: "Production sports feed",
    mode: "production",
    status: "not_configured",
    lastSuccess: null,
    cadence: "Provider contract required",
    note: "No licensed production credentials configured.",
  },
  {
    id: "production-odds",
    label: "Licensed odds",
    mode: "production",
    status: "not_configured",
    lastSuccess: null,
    cadence: "Provider-safe cadence required",
    note: "No market feed or display rights configured.",
  },
  {
    id: "production-email",
    label: "Email delivery",
    mode: "production",
    status: "not_configured",
    lastSuccess: null,
    cadence: "Event driven",
    note: "Development mail sink is local-only; no campaign can send.",
  },
  {
    id: "production-partners",
    label: "Commercial partners",
    mode: "production",
    status: "not_configured",
    lastSuccess: null,
    cadence: "Registry review",
    note: "No affiliate or advertising programs are active.",
  },
];

export function getTeam(teamId: string) {
  const team = teams.find((candidate) => candidate.id === teamId);
  if (!team) throw new Error(`Unknown fixture team id: ${teamId}`);
  return team;
}

export function getTeamBySlug(slug: string) {
  return teams.find((team) => team.slug === slug);
}

export function getGame(gameId: string) {
  return games.find((game) => game.id === gameId);
}

export function getCoachBySlug(slug: string) {
  return coaches.find((coach) => coach.slug === slug);
}

export function getStadiumBySlug(slug: string) {
  return stadiums.find((stadium) => stadium.slug === slug);
}
